version: '3.4'

services:
  drone-server:
    image: drone/drone
    networks:
      - default
      - traefik-net
    ports:
      - 8888:8000
    volumes:
      - /Users/smithc40/drone:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_DEBUG=true
      - DRONE_HOST=http://locahost:8888
      - DRONE_GOGS=true
      - DRONE_ADMIN=nctiggy,yetiwilson
      - DRONE_GOGS_URL=http://gogs-server:3000
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_SECRET=61C6082F-922B-4CCD-A1FA-701A49F1126D
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8000"
        - "traefik.frontend.rule=Host:drone.bellevuelab.isus.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

  drone-agent:
    image: drone/agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=61C6082F-922B-4CCD-A1FA-701A49F1126D

networks:
  traefik-net:
    external: true
