version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    networks:
      - logs-net
      - traefik-net
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      labels:
        - "traefik.port=9200"
        - "traefik.frontend.rule=Host:elasticsearch.bellevuelab.isus.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.2
    networks:
      - logs-net
      - traefik-net
    configs:
      - source: logstash_conf
        target: /usr/share/logstash/pipeline/logstash.conf
        mode: 444
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      labels:
        - "traefik.port=9600"
        - "traefik.frontend.rule=Host:logstash.bellevuelab.isus.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
    networks:
      - logs-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    dns: 127.0.0.11
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    networks:
      - traefik-net
      - logs-net
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1
      labels:
        - "traefik.port=5601"
        - "traefik.frontend.rule=Host:logs.bellevuelab.isus.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

volumes:
  esdata:
    driver: rexray/scaleio
    driver_opts:
      size: 200

configs:
  logstash_conf:
    file: logstash.conf

networks:
  traefik-net:
    external: true
  logs-net:
    external: true
