version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    deploy:
      replicas: 1

volumes:
  mongo:
    driver: vsphere
    driver_opts:
      size: 50gb
