version: '3.4'

services:
  server:
    image: portainer/portainer
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:manage.container.se.lab.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
  visualizer:
    image: dockersamples/visualizer
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:visualizer.container.se.lab.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

volumes:
  portainer:
    driver: vsphere
    driver_opts:
      size: 100gb

networks:
  traefik-net:
    external: true
