version: '3'

services:
  files:
    image: rackhd/files
    volumes:
      - files:/RackHD/files

volumes:
  files:
    driver: local
    driver_opts:
      type: nfs
      o: addr=freenas.bluehairfreak.com,rw
      device: ":/mnt/media/rackhd"

networks:
  traefik-net:
    external: true
  hostnet:
    external:
      name: host
