version: '3.4'

services:
  server:
    image: rancher/server:stable
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.frontend.rule=Host:rancher.bellevuelab.isus.emc.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  traefik-net:
    external: true
