version: '3'

services:
  server:
    image: registry
    networks:
      - traefik-net
      - default
    volumes:
      - server:/var/lib/registry
    deploy:
      replicas: 1
      labels:
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:hub.bluehairfreak.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

volumes:
  server:
    driver: rexray/scaleio
    driver_opts:
      size: 500

networks:
  traefik-net:
    external: true
