version: '3.3'

services:
  traefik:
    image: traefik
    networks:
      - traefik-net
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 444
    secrets:
      - source: traefik_cert
        target: cert.pem
        uid: "0"
        mode: 400
      - source: traefik_key
        target: key.pem
        uid: "0"
        mode: 400
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:proxy.bluehairfreak.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

networks:
  traefik-net:
    external: true

configs:
  traefik_toml:
    file: ./traefik.toml

secrets:
  traefik_cert:
    file: ./lab.crt
  traefik_key:
    file: ./lab.key
