version: '3.3'

services:
  traefik:
    image: traefik
    networks:
      - traefik-net
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 444
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:proxy.container.se.lab.emc.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

networks:
  traefik-net:
    external: true

configs:
  traefik_toml:
    file: ./traefik.toml
