version: '3.4'

services:
  vault:
    image: vault
    networks:
      - traefik-net
    volumes:
      - vault:/vault/file
    environment:
      - VAULT_LOCAL_CONFIG="{"backend": {"file": {"path": "/vault/file"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}"
    entrypoint:
      - vault server -config=/vault/config/vault.json
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8200"
        - "traefik.frontend.rule=Host:vault.bellevuelab.isus.emc.com"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"

volumes:
  vault:
    driver: rexray/scaleio
    driver_opts:
      size: 48

networks:
  traefik-net:
    external: true
