version: '3.3'

services:
  hello-world:
    image: tutum/hello-world
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.frontend.rule=Host:helloworld.bellevuelab.isus.emc.com"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
      replicas: 3

networks:
  traefik-net:
    external: true
